In [1]:
import pandas as pd
import os

access_electricity_data= os.path.join("Resources/API_EG.ELC.ACCS.ZS_DS2_en_csv_v2_714075.csv")
access_electricity_df=pd.read_csv(access_electricity_data, skiprows=4)
access_electricity_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 64
0,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.0,100.0,100.000000,100.00000,NaN,NaN,NaN
1,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,43.222019,69.100000,70.153481,89.5,71.5,97.700000,97.70000,NaN,NaN,NaN
2,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,34.600000,35.670788,36.878685,32.0,42.0,40.624527,41.88623,NaN,NaN,NaN
3,Albania,ALB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.0,100.0,100.000000,100.00000,NaN,NaN,NaN
4,Andorra,AND,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.0,100.0,100.000000,100.00000,NaN,NaN,NaN