In [1]:
import pandas as pd
import os

access_electricity_data= os.path.join("Resources/API_EG.ELC.ACCS.ZS_DS2_en_csv_v2_714075.csv")
access_electricity_df=pd.read_csv(access_electricity_data, skiprows=4)
access_electricity_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 64
0,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.0,100.000000,100.000000,100.000000,NaN,NaN,NaN
1,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,43.222019,69.100000,70.153481,89.5,71.500000,97.700000,97.700000,NaN,NaN,NaN
2,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,34.600000,35.670788,36.878685,32.0,42.000000,40.624527,41.886230,NaN,NaN,NaN
3,Albania,ALB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.0,100.000000,100.000000,100.000000,NaN,NaN,NaN
4,Andorra,AND,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.0,100.000000,100.000000,100.000000,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.0,100.000000,100.000000,100.000000,NaN,NaN,NaN
260,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.633110,69.433235,75.600000,66.1,74.268372,76.066811,79.200000,NaN,NaN,NaN
261,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,84.700000,85.300000,85.400000,86.0,85.500000,84.200000,84.400000,NaN,NaN,NaN
262,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,26.440128,27.211624,28.089314,27.9,31.100000,35.216507,40.300000,NaN,NaN,NaN
263,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,36.900000,44.000000,38.344547,32.3,33.700000,39.892345,40.421368,NaN,NaN,NaN