In [6]:
import pandas as pd
import os

climate_change_data= os.path.join("Resources/API_19_DS2_en_csv_v2_713902.csv")
climate_change_df=pd.read_csv(climate_change_data, skiprows=4)
climate_change_df.head(30)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 64
0,Aruba,ABW,Urban population (% of total population),SP.URB.TOTL.IN.ZS,50.776000,50.761000,50.746000,50.730000,50.715000,50.700000,...,42.940000,42.957000,42.990000,43.041000,43.108000,43.192000,43.293000,43.411000,NaN,NaN
1,Aruba,ABW,Urban population,SP.URB.TOTL,27526.000000,28141.000000,28532.000000,28761.000000,28924.000000,29082.000000,...,43819.000000,44057.000000,44348.000000,44665.000000,44979.000000,45296.000000,45616.000000,45948.000000,NaN,NaN
2,Aruba,ABW,Urban population growth (annual %),SP.URB.GROW,3.117931,2.209658,1.379868,0.799404,0.565140,0.544773,...,0.093611,0.541674,0.658336,0.712259,0.700552,0.702301,0.703980,0.725179,NaN,NaN
3,Aruba,ABW,"Population, total",SP.POP.TOTL,54211.000000,55438.000000,56225.000000,56695.000000,57032.000000,57360.000000,...,102046.000000,102560.000000,103159.000000,103774.000000,104341.000000,104872.000000,105366.000000,105845.000000,NaN,NaN
4,Aruba,ABW,Population growth (annual %),SP.POP.GROW,3.148037,2.238144,1.409622,0.832453,0.592649,0.573468,...,0.370125,0.502430,0.582349,0.594397,0.544892,0.507618,0.469944,0.453576,NaN,NaN
5,Aruba,ABW,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Aruba,ABW,"Prevalence of underweight, weight for age (% o...",SH.STA.MALN.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Aruba,ABW,"Community health workers (per 1,000 people)",SH.MED.CMHW.P3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Aruba,ABW,"Mortality rate, under-5 (per 1,000 live births)",SH.DYN.MORT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Aruba,ABW,"Primary completion rate, total (% of relevant ...",SE.PRM.CMPT.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,96.570640,101.180600,NaN,NaN,NaN,NaN,NaN,NaN
10,Aruba,ABW,"School enrollment, primary and secondary (gros...",SE.ENR.PRSC.FM.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.008710,1.021560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Aruba,ABW,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Aruba,ABW,CPIA public sector management and institutions...,IQ.CPA.PUBS.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Aruba,ABW,Ease of doing business index (1=most business-...,IC.BUS.EASE.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Aruba,ABW,Terrestrial and marine protected areas (% of t...,ER.PTD.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.527983,0.141163,0.141163,NaN,NaN
15,Aruba,ABW,Marine protected areas (% of territorial waters),ER.MRN.PTMR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000105,0.000105,NaN,NaN
16,Aruba,ABW,Terrestrial protected areas (% of total land a...,ER.LND.PTLD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.530000,18.917576,18.917576,NaN,NaN
17,Aruba,ABW,"Annual freshwater withdrawals, total (% of int...",ER.H2O.FWTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Aruba,ABW,"Annual freshwater withdrawals, total (billion ...",ER.H2O.FWTL.K3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Aruba,ABW,Population in urban agglomerations of more tha...,EN.URB.MCTY.TL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Aruba,ABW,Population living in areas where elevation is ...,EN.POP.EL5M.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Aruba,ABW,Urban population living in areas where elevati...,EN.POP.EL5M.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Aruba,ABW,Rural population living in areas where elevati...,EN.POP.EL5M.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Aruba,ABW,"Droughts, floods, extreme temperatures (% of p...",EN.CLC.MDAT.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Aruba,ABW,GHG net emissions/removals by LUCF (Mt of CO2 ...,EN.CLC.GHGR.MT.CE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Aruba,ABW,Disaster risk reduction progress score (1-5 sc...,EN.CLC.DRSK.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Aruba,ABW,SF6 gas emissions (thousand metric tons of CO2...,EN.ATM.SF6G.KT.CE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Aruba,ABW,PFC gas emissions (thousand metric tons of CO2...,EN.ATM.PFCG.KT.CE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Aruba,ABW,Nitrous oxide emissions (% change from 1990),EN.ATM.NOXE.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-45.657571,-45.119527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Aruba,ABW,Nitrous oxide emissions (thousand metric tons ...,EN.ATM.NOXE.KT.CE,NaN,NaN,NaN,NaN,NaN,NaN,...,6.425156,6.488772,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN