In [1]:
import pandas as pd
import os

renew_energy_consumpt_data= os.path.join("Resources/API_EG.FEC.RNEW.ZS_DS2_en_csv_v2_716974.csv")
renew_energy_consumpt_df=pd.read_csv(renew_energy_consumpt_data, skiprows=4)
renew_energy_consumpt_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 64
0,Aruba,ABW,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.661788,6.855850,6.889753,6.927502,6.726748,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,11.482706,13.973586,16.334293,19.314269,18.423477,NaN,NaN,NaN,NaN,NaN
2,Angola,AGO,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,52.715679,52.245736,50.686116,50.797461,49.568210,NaN,NaN,NaN,NaN,NaN
3,Albania,ALB,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,35.962532,40.048300,41.288974,38.689501,38.615210,NaN,NaN,NaN,NaN,NaN
4,Andorra,AND,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.971546,19.195529,19.563698,19.886323,19.747809,NaN,NaN,NaN,NaN,NaN