In [1]:
import pandas as pd
import os

pop_grow_data= os.path.join("API_SP.POP.GROW_DS2_en_csv_v2_715046.csv")
pop_grow_df=pd.read_csv(pop_grow_data, skiprows=4)
pop_grow_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 64
0,Aruba,ABW,Population growth (annual %),SP.POP.GROW,3.148037,2.238144,1.409622,0.832453,0.592649,0.573468,...,0.370125,0.502430,0.582349,0.594397,0.544892,0.507618,0.469944,0.453576,NaN,NaN
1,Afghanistan,AFG,Population growth (annual %),SP.POP.GROW,1.828639,1.898476,1.965751,2.029893,2.090248,2.147567,...,3.143126,3.407587,3.494589,3.355582,3.077084,2.778317,2.548347,2.384761,NaN,NaN
2,Angola,AGO,Population growth (annual %),SP.POP.GROW,1.369926,1.393363,1.383629,1.256555,0.973962,0.617544,...,3.634159,3.597774,3.551950,3.497493,3.438851,3.378273,3.322081,3.276134,NaN,NaN
3,Albania,ALB,Population growth (annual %),SP.POP.GROW,3.015423,3.120855,3.056731,2.953749,2.880686,2.754021,...,-0.269017,-0.165151,-0.183211,-0.207047,-0.291206,-0.159880,-0.091972,-0.246732,NaN,NaN
4,Andorra,AND,Population growth (annual %),SP.POP.GROW,7.050663,6.941532,6.692697,6.559522,6.241511,5.998800,...,-0.834745,-1.588730,-2.025792,-1.951470,-1.529058,-0.919470,-0.383674,0.006493,NaN,NaN